{% set name = "wind-stats" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wind-stats-{{ version }}.tar.gz
  sha256: 520b97252167cfb7dc225f3bfc9c51cff41fcce177a90d0d3807227e9ec2324e

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry-core >=1.0.0,<2.0.0
  run:
    - importlib-metadata >=3.4.0,<4.0.0
    - numpy >=1.19.4,<2.0.0
    - pint >=0.17.0,<0.18.0
    - python >={{ python_min }}
    - scipy >=1.5.4,<2.0.0
    - typing-extensions >=3.7.4,<4.0.0
    - xarray >=0.17.0,<0.18.0

test:
  imports:
    - wind_stats
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jules-ch/wind-stats
  summary: Statistics tools to evaluate your wind energy projects
  license: MIT
  license_file: LICENSE
  doc_url: https://wind-stats.readthedocs.io/
  dev_url: https://github.com/jules-ch/wind-stats

extra:
  recipe-maintainers:
    - jules-ch
